/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import massalud.AccesoADatos.especialidadData;
import massalud.AccesoADatos.prestadorData;
import massalud.Entidades.*;

/**
 *
 * @author sergi
 */
public class VistaMenuPrestadores extends javax.swing.JInternalFrame {
    private prestadorData prest = new prestadorData();
    private especialidadData esp = new especialidadData();
    private ArrayList<Especialidad> listaEsp;
    /**
     * Creates new form VistaMenuPrestadores
     */
    public VistaMenuPrestadores() {
        initComponents();
        listaEsp = (ArrayList<Especialidad>)esp.listarEspecialidades();
        cargarCheckBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSalida = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDocumento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        jApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDomicilio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jEstado = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jAgregar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jCombo = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("PRESTADORES");

        jSalida.setText("Salida");
        jSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalidaActionPerformed(evt);
            }
        });

        jLabel2.setText("Documento:");

        jButton1.setText("Buscar");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jApellidoActionPerformed(evt);
            }
        });

        jLabel5.setText("Domicilio:");

        jLabel6.setText("Telefono:");

        jTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelefonoActionPerformed(evt);
            }
        });

        jLabel7.setText("Estado:");

        jLabel8.setText("Especialidad:");

        jAgregar.setText("Agregar");
        jAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");

        jButton4.setText("Modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jEstado)
                                .addComponent(jTelefono)
                                .addComponent(jCombo, 0, 195, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jAgregar)
                        .addGap(29, 29, 29)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSalida)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEstado)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSalida)
                    .addComponent(jAgregar)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalidaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jSalidaActionPerformed

    private void jApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jApellidoActionPerformed

    private void jTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTelefonoActionPerformed

    private void jAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarActionPerformed
        // TODO add your handling code here:
        try{
            String dniTexto = jDocumento.getText();
            String telefonoTexto = jTelefono.getText();
            
            //validacion de cantidad de caracteres en documento y telefono celular
            if(telefonoTexto.length() != 10){
                JOptionPane.showMessageDialog(null, "el numero de telefono es muy corto o paso los limites de 10 digitos");
                return;
            }
            
            if(dniTexto.length()!= 8){
                JOptionPane.showMessageDialog(null, "el numero de Documento es invalido");
                return;
            }
            
            int dni = Integer.parseInt(dniTexto);
            String nombre = jNombre.getText();
            String apellido = jApellido.getText();
            String domicilio = jDomicilio.getText();
            long telefono = Long.parseLong(telefonoTexto);
            boolean estado =  jEstado.isSelected();
        
            Especialidad es = (Especialidad)jCombo.getSelectedItem();
        
        //Validacion de datos ingresados en nombre, apellido,domicilio
        if(!esString(nombre)){
            throw new IllegalArgumentException("el bloque nombre es invalido, Revicelo por favor");
        }else if(!esString(apellido)){
            throw new IllegalArgumentException("el bloque apellido es invalido, Revicelo por favor");
        }else if(!esString(domicilio)){
            throw new IllegalArgumentException("el bloque domicilio es invalido, Revicelo por favor");
        }
         //validacion de si existe el documento   
        if(prest.ValidacionDni(dni)){
        
            JOptionPane.showMessageDialog(null, "El dni o documento ya esta en la Base de Datos");
            eliminardtos();
        
        }else{
            System.out.println("hola");
         Prestador agregarPrestador = new Prestador();
        
            agregarPrestador.setDni(dni);
            agregarPrestador.setNombre(nombre);
            agregarPrestador.setApellido(apellido);
            agregarPrestador.setDomicilio(domicilio);
            agregarPrestador.setTelefono(telefono);
            agregarPrestador.setEstado(estado);
            agregarPrestador.setEspecialidad(es);
            prest.guardarPrestadores(agregarPrestador);
        
            System.out.println(agregarPrestador);
        
        }
            
        }catch(NumberFormatException e){
        
        JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }catch(NullPointerException e){
        
            JOptionPane.showMessageDialog(null,"Hay datos vacios"+ e.getLocalizedMessage());
        
        }catch(IllegalArgumentException ex){
            JOptionPane.showMessageDialog(null, "Error al guardar los datos "+ ex.getLocalizedMessage());
            
        }
    }//GEN-LAST:event_jAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAgregar;
    private javax.swing.JTextField jApellido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<Especialidad> jCombo;
    private javax.swing.JTextField jDocumento;
    private javax.swing.JTextField jDomicilio;
    private javax.swing.JRadioButton jEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jNombre;
    private javax.swing.JButton jSalida;
    private javax.swing.JTextField jTelefono;
    // End of variables declaration//GEN-END:variables
 public void eliminardtos(){
     
     jDocumento.setText("");
     jNombre.setText("");
     jApellido.setText("");
     jDomicilio.setText("");
     jTelefono.setText("");
     jEstado.setSelected(false);
 }
 
 public void cargarCheckBox(){
     
     for(Especialidad ep : listaEsp){
         
         jCombo.addItem(ep);
     }
 
 
 }
 
 private boolean esString(String letra){
 
     if(letra == null || letra.trim().isEmpty()){
     return false;
     
     }
     return letra.matches("^[a-zA-Z ]+$");
 }
 
}

